### ISSUE TITLE
Privacy Consideration section

### ISSUE THREAD

**Issue by kkoiwai** [gruposantander/digital-trust-assertion-claims-specs#2]
Thanks for the spec draft!

I think there should be a Privacy Consideration section at the bottom, such as:

> The `assertion_claims` can contain Personally Identifiable Information (PII). As such, RP should obtain End-User consent for the release of the information at or prior to the request in accordance with relevant regulations. 
> 
> How to get such consent is out of scope for this specification.
> 
> The OP should not keep the information within `assertion_claims` unless necessary and should delete such information as soon as it is no longer necessary in accordance with relevant regulations.

**Comment by victorherraiz-santander** [comment]
Thank you so much. We will add the section as you suggested
